### ISSUE TITLE
Diffpure experiment evaluation settings

### ISSUE THREAD

**Issue by YUHAOSUNABC** [ml-postech/robust-evaluation-of-diffusion-based-purification#1]
Hi, thanks for your great work. I am trying to recover the results of diffpure method under your evaluation settings. I have noticed that you are using a surrogate method, could you please provide the parameter settings when you run diffpure experiment? Thanks a lot!

**Comment by Minjong-Lee** [comment]
Sorry for the delayed response. 

As you said, to address the memory issue of the full-gradient attack, we implemented a surrogate process. The memory issue in DiffPure's full-gradient attack arises due to using t* = 0.1 with a step size of 0.001, leading to 100 denoising steps. In the DiffPure paper, they solve this issue by implementing an adjoint method for the full-gradient attack.

For our attack using the surrogate process, we increased the step size when generating adversarial images. Specifically, for the DiffPure case (as shown in Table 7 of our paper), we used a step size of 0.005 (20 steps) for the attack. As I recall, calculating gradients over 20 steps required nearly 80GB of GPU memory.

To evaluate DiffPure, we used the original DiffPure GitHub repository. You can use 'torchsde.sdeint' for the full-gradient attack with the surrogate process and change the step size in 'torchsde.sdeint'. In our evaluation, we cloned the DiffPure GitHub repository and created two pipelines: one for attack generation using a step size of 0.005, and another for the defense process using a step size of 0.001. Implementing this requires only a simple code modification. However, since DiffPure is based on the ScoreSDE framework and our implementation uses the DDPM/DDIM framework, the DiffPure results cannot be reproduced using our repository.

**Comment by YUHAOSUNABC** [comment]
Thanks for your reply! I have a further question regarding score SDE. I found both the standard and robust accuracies of diffpure are quite similar when utilizes different sampling method, such as the DDPM/DDIM in your implementation and the sdeint solver in Diffpure's implementation. In your opinion, would you accept evaluating Diffpure under your implementations, which is setting att_diffusion_step to 20 (equals setting dt = 0.005 in sdeint)?

**Comment by Minjong-Lee** [comment]
In my opinion, the setting you mentioned cannot be considered as the original results from the DiffPure paper. However, since DiffPure should be agnostic to the sampling method, if you want to use our implementation, it would be fine as long as you mention that only the sampling framework was changed to DDPM/DDIM.

**Comment by YUHAOSUNABC** [comment]
> In my opinion, the setting you mentioned cannot be considered as the original results from the DiffPure paper. However, since DiffPure should be agnostic to the sampling method, if you want to use our implementation, it would be fine as long as you mention that only the sampling framework was changed to DDPM/DDIM.

Thanks for your reply!
